### ISSUE TITLE
Rating an album

### ISSUE THREAD

**Issue by Akasiek** [brimell/spicetify-star-ratings#2]
Hi! Continuing my little rant...

In the original extension there was an indicator on the album page that added up the stars of all the songs, calculated the average of the ratings and displayed it as the album rating.

It was my idea and the issue is here: https://github.com/duffey/spicetify-star-ratings/issues/3

Can you bring it back? Or maybe add an option to rate the album yourself and have the calculation visible somewhere else? Appreciate it!

**Comment by brimell** [comment]
Hi there,

So sorry for the late reply. It seems not to be working when using it through the spicetify marketplace however works fine when you download the star-ratings.js file from the dist folder and place it in your ...\AppData\Roaming\spicetify\Extensions folder with a spicetify config that looks like the following:

```
[AdditionalOptions]
extensions            = star-ratings.js
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1
```

![image](https://github.com/brimell/spicetify-star-ratings/assets/69201936/ee1e6a19-6add-4b9d-84fa-cf9d7e7bb97d)

**Comment by brimell** [comment]
Again, sorry for the late reply but I was also wondering about changing the album rating to just a rating and not an average - the only problem with this is storage. Currently, the song ratings are stored through spotify in folders but I'm not sure about storing a rating for an album at the moment. If anyone has some good suggestions please let me know maybe in another issue?

**Comment by Akasiek** [comment]
Thanks for the replay, but I wouldn't consider it closed. Most people use the Marketplace to install extensions. Can you try to fix it for Marketplace?

**Comment by brimell** [comment]
On it!

**Comment by brimell** [comment]
Will check back in tomorrow - jsdelivr cdn takes 12 hours to update so the development/debugging process is annoyingly slow 😢 but I think my fixes should work 👍

**Comment by brimell** [comment]
Seems to be working through spicetify marketplace now! Thanks for letting me know about the issue ❤️

**Comment by Akasiek** [comment]
![image](https://github.com/brimell/spicetify-star-ratings/assets/37307597/1bd0f927-966d-46cb-8130-c5beb08d9fd8)

Working great! Thank you!

**Comment by Akasiek** [comment]
> Again, sorry for the late reply but I was also wondering about changing the album rating to just a rating and not an average - the only problem with this is storage. Currently, the song ratings are stored through spotify in folders but I'm not sure about storing a rating for an album at the moment. If anyone has some good suggestions please let me know maybe in another issue?

I was recently thinking about this and maybe SQLite would work for this. You could enable this option by plugging in SQLite hosting address. Something like https://sqlitecloud.io?

**Comment by brimell** [comment]
Yeah so would you not still need users to have accounts then to login and sync etc. Could do it by IP ig but I prefer accounts to that. If I have time I might get round to it but unfortunately I'm quite busy atm
