### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by Dave---** [brimell/spicetify-star-ratings#6]
Is there any way to synchronise ratings between multiple devices (both running spicetify, etc)?

Even if I need to do it manually, where and which files would I need to copy/sync?

**Comment by Florry** [comment]
The rated songs are saved to playlists in your spotify account, so you don't need to do anything for it to sync between different devices, just use the extension and it will pick them up automatically

**Comment by Dave---** [comment]
The song are in the correct playlists, but the actual stars don't sync across.

For example, some songs in my "4 star" playlist on my laptop do not have a 4 star rating and vice versa....

**Comment by SirSragus** [comment]
If you restart Spotify on the 2nd device, the stars should appear.

**Comment by brimell** [comment]
Hi there,

Sorry for the late reply. What @Florry and @SirSragus said is correct however if you are still having problems I would recommend downloading the star-ratings.js file from the dist folder and placing it in the ...\AppData\Roaming\spicetify\Extensions folder and your spicetify config should look something like the following:

```
[Setting]
spotify_path           = C:\Users\billj\AppData\Roaming\Spotify
current_theme          = marketplace
inject_css             = 1
overwrite_assets       = 0
spotify_launch_flags   = 
prefs_path             = C:\Users\billj\AppData\Roaming\Spotify\prefs
color_scheme           = 
inject_theme_js        = 1
replace_colors         = 1
check_spicetify_update = 1
always_enable_devtools = 0

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

[AdditionalOptions]
extensions            = star-ratings.js
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.38.720.ga4a70a0e
with    = 2.36.11
```

just a note: if any updates are made to the extension you will need to download a new version so keep that in mind
