### ISSUE TITLE
add a 0 star playlist icon

### ISSUE THREAD

**Issue by brimell** [brimell/spicetify-star-ratings#9]
I forgot to make a 0 star playlist icon when i originally made them...
![image](https://github.com/brimell/spicetify-star-ratings/assets/69201936/10bc0877-73ee-4621-ad60-617972df69ec)

**Comment by Mosuki0** [comment]
![0star](https://github.com/brimell/spicetify-star-ratings/assets/125518064/0203de42-498d-4c2f-94e0-179d1928159d)
like this?
